[common]
server_addr = "167.234.231.216"
server_port = 7000
log_level = "debug"

# Cada proxy deve ficar dentro de um bloco [[proxies]]
[[proxies]]
name = "win_shell"
type = "tcp"
local_ip = "127.0.0.1"
local_port = 4444
remote_port = 14791
